# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "technologies"

# This page should be the root of your website. It's important.
page = "https://lopsided-soul-f8d.notion.site/GS-Technologies-c88a97fa4fcf437ca8011886659f7460"
